FROM --platform=linux/amd64 quay.io/rockylinux/rockylinux-shim:9 AS amd64
ENV EL_PLATFORM el9
ENV SHIM_VERSION 16.1-3.$EL_PLATFORM

COPY rpmmacros /root/.rpmmacros
COPY shim-unsigned-x64-$SHIM_VERSION.src.rpm /
RUN rm -rfv /etc/yum.repos.d/*
RUN rpm -ivh shim-unsigned-x64-$SHIM_VERSION.src.rpm
RUN sed -i 's/linux32 -B/linux32/g' /builddir/build/SPECS/shim-unsigned-x64.spec
RUN dnf builddep -y /builddir/build/SPECS/shim-unsigned-x64.spec
RUN rpmbuild -bb /builddir/build/SPECS/shim-unsigned-x64.spec

RUN mkdir /built_shim/
COPY shimx64.nx.efi /

RUN rpm2cpio /builddir/build/RPMS/x86_64/shim-unsigned-x64-$SHIM_VERSION.x86_64.rpm | cpio -diu -D /built_shim
RUN ls -l /*.efi /built_shim/usr/share/shim/$SHIM_VERSION/*/shim*.efi

RUN sha256sum /built_shim/usr/share/shim/$SHIM_VERSION/x64/shimx64.nx.efi /shimx64.nx.efi

RUN hexdump -Cv /built_shim/usr/share/shim/$SHIM_VERSION/x64/shimx64.nx.efi > built-x64.hex

RUN hexdump -Cv /shimx64.nx.efi > orig-x64.hex

RUN diff -u orig-x64.hex built-x64.hex

RUN cmp /built_shim/usr/share/shim/$SHIM_VERSION/x64/shimx64.nx.efi /shimx64.nx.efi

RUN pesign -h -P -i /built_shim/usr/share/shim/$SHIM_VERSION/x64/shimx64.nx.efi

RUN pesign -h -P -i /shimx64.nx.efi

RUN sha256sum /built_shim/usr/share/shim/$SHIM_VERSION/x64/shimx64.nx.efi /shimx64.nx.efi
